init:
	python3 -m venv venv & source venv/bin/activate & pip install pytest requests & pytest -v test_jsonplaceholder.py

init-mac:
	python3 -m venv venv && . venv/bin/activate && python3 -m pip install pytest requests && pytest -v test_jsonplaceholder.py